"""initial migration

Revision ID: 04fe3632c1fb
Revises: 
Create Date: 2023-04-23 22:55:05.194605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04fe3632c1fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('distribuidor', sa.String(length=255), nullable=True),
    sa.Column('ASIN', sa.String(length=255), nullable=True),
    sa.Column('EAN', sa.Numeric(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_ASIN'), ['ASIN'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_EAN'), ['EAN'], unique=False)

    op.create_table('precios_historicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('precios_historicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_precios_historicos_fecha'), ['fecha'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('precios_historicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_precios_historicos_fecha'))

    op.drop_table('precios_historicos')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_EAN'))
        batch_op.drop_index(batch_op.f('ix_productos_ASIN'))

    op.drop_table('productos')
    # ### end Alembic commands ###
