"""Initial migration

Revision ID: 1d8d85e1c37b
Revises: 
Create Date: 2023-04-30 11:23:25.682869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8d85e1c37b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('ASIN', sa.String(length=255), nullable=True),
    sa.Column('EAN', sa.Numeric(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_ASIN'), ['ASIN'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_EAN'), ['EAN'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('historicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('id_vendedor', sa.String(length=255), nullable=False),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historicos_fecha'), ['fecha'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historicos_fecha'))

    op.drop_table('historicos')
    op.drop_table('users')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_EAN'))
        batch_op.drop_index(batch_op.f('ix_productos_ASIN'))

    op.drop_table('productos')
    # ### end Alembic commands ###
